const data = {
  products: [
    {
      id: 1,
      name: "Nike Shirt",
      slug: "nike-shirt",
      catagory: "Shirts",
      image: "/images/p1.jpg",
      price: 119.99,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 2,
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      catagory: "Shirts",
      image: "/images/p2.jpg",
      price: 99.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 3,
      name: "Nike White Shirt",
      slug: "nike-white-shirt",
      catagory: "Shirts",
      image: "/images/p3.jpg",
      price: 114.99,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 4,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p4.jpg",
      price: 99.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 5,
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      catagory: "Shirts",
      image: "/images/cloth1.jpg",
      price: 99.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 6,
      name: "Adidas Shirt",
      slug: "adidas-shirt",
      catagory: "Shirts",
      image: "/images/cloth2.jpg",
      price: 79.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 7,
      name: "Adidas White Shirt",
      slug: "adidas-white-shirt",
      catagory: "Shirts",
      image: "/images/cloth3.jpg",
      price: 79.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 8,
      name: "Adidas T-shirt",
      slug: "adidas-T-shirt",
      catagory: "Shirts",
      image: "/images/cloth4.jpg",
      price: 99.99,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
  ],
};
module.exports = data;
