const data = {
  products: [
    {
      id: 1,
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      catagory: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 2,
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      catagory: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 3,
      name: "Nike Slim Pants",
      slug: "nike-slim-Pants",
      catagory: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: 4,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 5,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 6,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 7,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      id: 8,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
  ],
};
export default data;
