const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      catagory: "Shirts",
      image: "p1",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: 2,
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      catagory: "Shirts",
      image: "p2",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: 3,
      name: "Nike Slim Pants",
      slug: "nike-slim-Pants",
      catagory: "Shirts",
      image: "p3",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: 4,
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      catagory: "Shirts",
      image: "p4",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
  ],
};
export default data;
